# Controller Manager Configuration
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

# Controller Definitions
diff_cont:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    
    # Names of the joints to control
    left_wheel_names: ["fl_joint", "rl_joint"]
    right_wheel_names: ["fr_joint", "rr_joint"]

    # Physical properties of the robot (THESE ARE ESTIMATES)
    wheel_separation: 0.4  # meters
    wheel_radius: 0.1      # meters

    # Other parameters
    publish_rate: 50.0
    use_stamped_vel: false

# Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
